### ISSUE TITLE
Shift+Tab - ver 2

### ISSUE THREAD

**Issue by terrygibbs** [sillsdev/SpeechAnalyzer#38] opened 2021-08-30 07:45 UTC
Hi,

I now realize that I have miss-understood the use of the word "Graph" which I interpreted as "The main Window of the open file" which holds all of the Graphs verses the word "Graph" which actually means one of the "sub-Plot windows" that are within the main open file.

That is, I was thinking that Shift+Tab was always used to go from the Waveform Graph window in one file to the Waveform Graph window of another open file.

But the use of Shift+Tab in older versions of SA used this feature to move from one Graph (a Plot window within the open file) to another Graph in that same open file. For example, using Shift+Tab to move from Waveform, to Pitch, to Spectrogram within a single open file.

After some amount of searching I found that the following changes were made in the SA source code on Aug 7, 2015.

  - Modified shortcut keys for Alt-Tab and Shift-Tab.
     . Alt-Tab has been removed from usage.
     . Shift-Tab now selects the previous segment.

There was no comment as to why Alt+Tab was removed.
The Shift+Tab feature was changed to provide the convention of using tabs to move right and left: Tab and Shift+Tab.

It's clear that this change broke the feature in SA of "Select a new active graph.  Shift+Tab".
Unfortunately the feature of using Shift+Tab to move between multiples Graphs in a single file never got fixed.

I suggest that this issue be put on a to do list.

Terry

**Comment by darcywong00** [comment] 2021-09-06 04:33
Duplicate of #37

**Closed by darcywong00** 2021-09-06 04:33 UTC
