### ISSUE TITLE
SA takes too long to display the Formant Tracks

### ISSUE THREAD

**Issue by darcywong00** [sillsdev/SpeechAnalyzer#13] opened 2021-06-08 08:07 UTC
@terrygibbs has provided this document which outlines some ideas how the "Formant Tracks" issue in SA can be resolved.

> Formant Tracks are generated as a large group of data points and then presented at one time over the Spectrogram. It can take from 10 seconds to more than 30 minutes to generate a specific data set.

[The.Formant.Tracks.issue.v4.pdf](https://github.com/sillsdev/SpeechAnalyzer/files/6806938/The.Formant.Tracks.issue.v4.pdf)

**Comment by darcywong00** [comment] 2021-08-12 03:48
From the v3 spec
> If “Formant Tracks” is selected then “Apply” must be disabled and a validation test needs to be run to determine if the 2 cursors are correctly placed. If not, close this dialog and put up a new dialog that says the 2 cursors need to be re-located. The
situation is that the cursors are either too close together or too far apart for the process to work.
* Use the metric ‘too close together’ as: < 0.5 sec.
* Use the metric ‘too far apart’ as: >15 sec.

I suggest passing in the cursor positions and duration and disabling "formant tracks" if the duration is outside that range.
![spectrogram parameters](https://user-images.githubusercontent.com/7358010/129135494-66466cd9-28d3-44b1-925b-285d94c13bd1.png)

**Comment by darcywong00** [comment] 2021-08-12 07:57
Comments from @terrygibbs 

> It may be that a student would not yet understand the meaning of 'Adjust cursor duration..."
> So I would like to suggest one of these, based on how much text space you have:
>
>    Note: Separate the 2 cursors to be 0.5 sec to 15.0 sec apart to enable the formant tracks.
>    Note: Separate the cursors to be 0.5 sec to 15.0 sec apart to enable the formant tracks.
>    Note: Separate the cursors to be 0.5 sec to 15.0 sec apart to show the formant tracks.

**Comment by kgorham** [comment] 2021-10-06 01:06
@terrygibbs Hi Terry, Where are the latest release of SA being stored? thx.

**Comment by megahirt** [comment] 2021-10-06 05:41
> @terrygibbs Hi Terry, Where are the latest release of SA being stored? thx.

@kgorham as @darcywong00 points out, we are releasing both on https://software.sil.org/speech-analyzer/#downloads and on https://github.com/sillsdev/SpeechAnalyzer/releases/

**Comment by kgorham** [comment] 2021-10-08 02:10
@terrygibbs would you have a sample that takes a long time to process the format tracks? chfrench processes to quickly for me.

**Comment by kgorham** [comment] 2021-10-20 01:14
@megahirt Terry gave me a file that is useful for testing the ESC problem.  Is there a way I should get it to you for testing?  Its 'Lahu Shi 1-3.wav' about 4.1 MB.  Maybe you have it already?

**Comment by terrygibbs** [comment] 2021-10-20 10:26
Using the Formant Tracks.

This is how Speech Analyzer currently works...

The Formant Tracks button that's in the middle of Task Bar, and the Formant Tracks option in the Graph Parameters dialog box, are linked together; they are either both on or both off. But by design they function in 2 different ways. 

When SA is first installed, the Formant Tracks button on the Task Bar is in the "Non-selected" mode. 

When the user opens a "Waveform" file and then selects the "Waveform, Spectrogram" option, then SA will show the Spectrogram, and SA will NOT generate Formants since the "Non-selected" mode is selected.

After showing a Spectrogram, then the user has 2 options for showing the Formant Tracks:

1.
If the user press the Formant Tracks button on the Task Bar, then SA will process the Formants and overlay the Formant Tracks onto the Spectrogram.

2.
If the user does a right mouse click in the Spectrogram plot to show the "Graph Parameters/ Spectrogram" dialog, and then selects the "Formant Tracks" check box and then selects the Apply button, then SA will process the Formants and display the Formant Tracks on the Spectrogram.

Note that in either one of these 2 cases the Formant Tracks have been displayed and thus the Formant Tracks option on the Task Bar is now shown as being in the "Selected" mode.


If the user closes SA and then double clicks on any .Wav file, then SA will show the Waveform. If the user then selects the "Waveform, Spectrogram" option, and since SA stored the fact that the Formant Tracks option was previously set to "Selected" mode, then SA will display a Spectrogram frame, then process the Formant data, and then display the Spectrogram and then overlay the "Formant Tracks" onto the Spectrogram.

What we need to do is restrict the amount of Formant data that is being generated.


---------------------------------------------------------

Changes that are needed.
========================

1.
When SA is launched, SA should always re-set the Formant Tracks option on the Task Bar to be in the "Non-selected" mode. Then if the user wants to show a Spectrogram, then there is no problem.

2.
If the user wants to show the Formant Tracks on that Spectrogram, and selects the Formant Tracks item on the Task Bar, then we need to do a test to see if the cursors are in the right place. If they are not then we need to display our pop-up screen to ask the user to first position the cursors, and try again.

3.
If the user wants to revise the Formant Tracks options on that Spectrogram, and the user does a right-mouse click on the Spectrogram plot and selects Graph Parameters/ Spectrogram and then select the Formant Tracks option, at that point we need to determine if the separation between the cursors is within our boundaries, if they are ok then we can continue. But if they are not in the correct range, then we need to put up a message that this dialog box will close so that the cursors can be positioned correctly. 

4.
If the user closes the Spectrogram window, then SA needs to immediately set SA to be in the "Non-selected" mode.


Note: I now suggest these setting for the cursors:

 . Use the metric ‘too close together’ as: < 1.0 sec.
 . Use the metric being ‘too far apart’ as: > 60 sec. 


Terry

**Comment by kgorham** [comment] 2021-10-21 01:24
@terrygibbs 
The 'bShowFormants' property is stored as an application property. Please consider the following use case:
1) The user opens SA and a WAVE file. 'show Formants' is disabled by default as requested.
2) The user enables 'show Formants'. Formants are displayed as expected.
3) The user opens a second WAVE file (first is still open).  Now 'show Formants' are still enabled.  Is this what we want?
Should we maintain this value on a per-document basis instead?

**Comment by kgorham** [comment] 2021-10-21 18:10
I think this got closed by mistake. I'm still working on it.

**Comment by kgorham** [comment] 2021-11-12 02:43
@terrygibbs 
If I:
1) open a project in SA, and display the waveform/spectrogram layout
2) and then click the 'formant tracks' toolbar icon so that it starts rendering the tracks
3) and then press escape to cancel processing (this wont work well for you)
4) sa will then display the 'process cancelled...' window
5) if I then click the 'formant tracks' toolbar icon to DISABLE the format tracks.  The 'process cancelled...' window wont go away.  I'm assuming it should go away. correct?

**Comment by kgorham** [comment] 2021-11-16 01:21
Is it just me? I don't know.  20 years later Hungarian notation just looks like a bad idea.

**Comment by kgorham** [comment] 2021-12-10 22:03
@megahirt @terrygibbs @darcywong00 i'm done with the changes for this issue.  I'm sorry this took so long.   I did a lot of messing around trying to fix a flickering problem when you resize a cancelled formanttrack window.  that is fixed. covid took me out for a couple weeks as well.  i've created a pull request.  Christopher, i'm not sure what the process is here, so tell me what I should do next.  do I need to write test steps.  If so, where?

**Comment by megahirt** [comment] 2021-12-11 04:36
@kgorham this is awesome - thank you for your work on this.  I think the best course of action is I and Darcy review your PR, and then Terry does the testing of a developer build after the PR is merged.

If the change can be captured using a screen recording/animation, that is a great way to demo it to me or Terry without us having to follow steps in the software itself.  I'm not really sure this change can be captured like that.

If you could add manual testing steps to the PR itself so that Terry can demo the fix, that would be best.

**Comment by kgorham** [comment] 2021-12-14 13:52
@megahirt @darcywong00 @terrygibbs heres a video showing before & after for the three problems that were fixed with this pull request.

https://user-images.githubusercontent.com/10772332/146010251-07f9e7cf-568b-4d2e-bb6e-7ea109ad7418.mp4

.

**Comment by megahirt** [comment] 2021-12-14 14:51
@kgorham well done!!!  Your demo video is first class.  This will be great to ship and get out to users!  @terrygibbs can you confirm your own testing in #56 ?

**Closed** 2022-02-28 07:17 UTC
Labels: enhancement
