### ISSUE TITLE
SA takes too long to display the Formant Tracks - Revised

### ISSUE THREAD

**Issue by terrygibbs** [sillsdev/SpeechAnalyzer#17] opened 2021-07-13 07:47 UTC
[The Formant Tracks issue v4.pdf](https://github.com/sillsdev/SpeechAnalyzer/files/6806879/The.Formant.Tracks.issue.v4.pdf)

**Comment by megahirt** [comment] 2021-07-13 07:54
duplicate of #13 .  We should close this issue and re-upload the v4 PDF to issue #13.

**Comment by megahirt** [comment] 2021-07-13 07:56
closed as duplicate after uploading v4 documentation to #13

**Closed by megahirt** 2021-07-13 07:56 UTC
